# Generated by Django 4.1 on 2023-10-19 19:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_stanowisko_osoba'),
    ]

    operations = [
        migrations.AddField(
            model_name='osoba',
            name='data_dodania',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='osoba',
            name='plec',
            field=models.IntegerField(choices=[(1, 'Kobieta'), (2, 'Mężczyzna'), (3, 'Inne')]),
        ),
        migrations.AlterField(
            model_name='stanowisko',
            name='nazwa',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='stanowisko',
            name='opis',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
