# Generated by Django 4.1 on 2023-12-15 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_osoba_wlasciciel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='osoba',
            options={'ordering': ['nazwisko'], 'permissions': [('can_view_other_persons', 'Pozwala wyświetlić obiekty Osoba, których zalogowany użytkownik nie jest właścicielem')]},
        ),
    ]
