# Generated by Django 4.1 on 2023-10-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_osoba_data_dodania_alter_osoba_plec_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osoba',
            name='data_dodania',
            field=models.DateField(auto_now=True),
        ),
    ]
