# Generated by Django 4.1 on 2023-12-15 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_osoba_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='osoba',
            options={'ordering': ['nazwisko'], 'permissions': [('can_view_other_persons', 'Pozwala wyświetlić wszystkie obiekty Osoba')]},
        ),
    ]
